name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build
          echo "yourdomain.com" > build/CNAME

      # Updated to use v4 of upload-artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Note: using v3 for pages-artifact
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3  # Updated to v3